# Generated by Django 5.2.4 on 2025-07-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Developer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("alias", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="devs/")),
            ],
        ),
    ]
