# Generated by Django 5.2.4 on 2025-07-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="projects/")),
                ("date", models.DateField(auto_now_add=True)),
                ("link", models.URLField()),
                ("git_id", models.IntegerField(unique=True)),
                (
                    "dev",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.developer",
                    ),
                ),
            ],
        ),
    ]
