# Generated by Django 5.2.4 on 2025-08-04 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="developer",
            options={
                "managed": True,
                "verbose_name": "Developer",
                "verbose_name_plural": "Developers",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "managed": True,
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="dev",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developers",
                to="core.developer",
            ),
        ),
    ]
