# Generated by Django 5.2.4 on 2025-08-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_developer_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="gist",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
