# Generated by Django 5.2.4 on 2025-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_project_gist_alter_project_git_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="dev",
        ),
        migrations.AddField(
            model_name="project",
            name="dev",
            field=models.ManyToManyField(
                related_name="developers", to="core.developer"
            ),
        ),
    ]
