# Generated by Django 5.2.4 on 2025-09-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_project_gist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gist",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
