# Generated by Django 5.2.4 on 2025-09-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_project_gist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="gist",
            field=models.URLField(blank=True, null=True),
        ),
    ]
