# Generated by Django 5.2.4 on 2026-04-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_project_gist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=150)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('resume_pdf', models.FileField(upload_to='resumes/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'managed': True,
            },
        ),
    ]
