# Generated by Django 5.2.4 on 2026-04-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='favorite_movie',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='interests',
            field=models.TextField(blank=True, help_text='Enter one interest per line.', null=True),
        ),
    ]
